# Rustfmt configuration for consistent code formatting
# https://rust-lang.github.io/rustfmt/

# Edition
edition = "2021"

# Maximum line width
max_width = 100

# Hard tabs or spaces
hard_tabs = false
tab_spaces = 4

# Newline style
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions
fn_single_line = false
fn_args_layout = "Tall"

# Structs and enums
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Match expressions
match_block_trailing_comma = true
match_arm_blocks = true
match_arm_leading_pipes = "Never"

# Comments
normalize_comments = true
wrap_comments = true
comment_width = 80

# Documentation
normalize_doc_attributes = true
format_code_in_doc_comments = true

# Chains
chain_width = 60
use_small_heuristics = "Default"

# Control flow
control_brace_style = "AlwaysSameLine"

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true
