[package]
name = "postgres-adapter"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
async-trait.workspace = true

pkg = { workspace = true }
core-db = { workspace = true }
baserepository = { workspace = true }
