[package]
name = "core-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
dotenvy.workspace = true
config = { workspace = true }
thiserror.workspace = true
